name: CI/CD for Lambda Publish

on:
  workflow_run:
    workflows: ["CI/CD for Layer Publish"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      #AWS_REGION: "ap-south-1"
      #AWS_REGION: $AWS_REGION
      AWS_REGION: "eu-west-1"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Create lambda function zip
        run: |
          echo "Creating lambda function zip"
          cd lambda_function
          zip -r ../lambda_function.zip lambda_function.py
          cd ..
          echo "Lambda function zip created"
          ls -al

      - name: Upload lambda function zip to S3
        run: |
          aws s3 cp lambda_function.zip s3://myc8-bucket-cicd/lambda_function.zip


 ##         
